Repository EwhaKing/king14-assignment, pull requests merged in 2024-03, with the labels that each got.

#38 [14기 최은별] git-github-1 과제😺
  README.md
  최은별/git-github-1/과제1.png
Labels: checked

#35 💚[14기 이도현] git-github-1 과제 제출
  README.md
  ldh:git-github-1/git_github_과제1.png
Labels: checked

#28 💚[14기 장한나] git-github-1
  README.md
Labels: more enhancement

#8 [14기 전희원] git_github1 과제 제출 (이모지!! 이거과제한거에요 이모지가안나와요ㅠㅠ)
  PR연습.txt
  User_information.png
Labels: checked

#20 ❄[14기 김유민] git-github-1 과제 제출
  Hello.txt
  README.md
  git-github-1/스크린샷 2024-03-28 200203.png
Labels: checked

#19 😺[13기 윤민주] git-github-1 과제 제출
  README.md
  git-github-1/과제1.png
  hello.txt
Labels: checked

#16 😎[13기 성원희] git-github-1 과제 제출
  13-swh.txt
  gitconfig.png
Labels: checked

#23 [13기 박시현] git-github-1 과제 제출
  README.md
  gitconfig.png
  hellopsy.txt
Labels: enhancement

#22 ✨[14기 이서우] git-github-1 과제 제출
  112.txt
  README.md
  [14기 이서우] git-github-1/git 교육 세션 1차시 과제.png
Labels: checked

#7 [14기 강다은] git_github_1 과제
  README.md
  git_github_1/화면 캡처 2024-03-28 171811.png
Labels: checked

#56 [14기 김여은] git-github-1 과제 제출
  README.md
  kye/git-github-1/과제1.png
Labels: checked

#29 😶‍🌫️[14기 김규림] git-github-1
  README.md
Labels: more enhancement

#39 [14기 안유경] git-github-1 과제 제출 😭
  Hello.txt
  README.md
  git-github-1/스크린샷 2024-03-31 193044.png
Labels: checked

#62 [14기 김규림] git-github-1
  김규림/이름_이메일저장위치.png
  이름이메일저장위치.png
Labels: checked
