Repository EwhaKing/king14-assignment, pull requests merged in 2024-06, with the labels that each got.

#135 [13기 박시현] Unity 2차시 세션 과제 제출
  unity2차시.pdf
Labels: checked, more enhancement

#131 [14기 유지우] 유니티 세션 1차시 과제
  KING_유니티세션_유지우.unitypackage
Labels: more enhancement

#145 [14기 김유민] Unity 세션 2차시 과제 제출
  KINGUnitySession2.pdf
Labels: checked

#147 [14기 강다형] C# 중급 세션 2차시, Unity 2차시 과제 제출
  .DS_Store
  C#_Assignment2.cs
  UnityEducation_02/.gitignore
  UnityEducation_02/.vscode/extensions.json
  UnityEducation_02/.vscode/launch.json
  UnityEducation_02/.vscode/settings.json
  UnityEducation_02/Assets/Movement2D.cs
  UnityEducation_02/Assets/Movement2D.cs.meta
  UnityEducation_02/Assets/Scenes.meta
  UnityEducation_02/Assets/Scenes/SampleScene.unity
  UnityEducation_02/Assets/Scenes/SampleScene.unity.meta
  UnityEducation_02/Assets/sauropod_1f995.png
  UnityEducation_02/Assets/sauropod_1f995.png.meta
  UnityEducation_02/Packages/manifest.json
  UnityEducation_02/Packages/packages-lock.json
  UnityEducation_02/ProjectSettings/AudioManager.asset
  UnityEducation_02/ProjectSettings/ClusterInputManager.asset
  UnityEducation_02/ProjectSettings/DynamicsManager.asset
  UnityEducation_02/ProjectSettings/EditorBuildSettings.asset
  UnityEducation_02/ProjectSettings/EditorSettings.asset
  UnityEducation_02/ProjectSettings/GraphicsSettings.asset
  UnityEducation_02/ProjectSettings/InputManager.asset
  UnityEducation_02/ProjectSettings/MemorySettings.asset
  UnityEducation_02/ProjectSettings/NavMeshAreas.asset
  UnityEducation_02/ProjectSettings/NetworkManager.asset
  UnityEducation_02/ProjectSettings/PackageManagerSettings.asset
  UnityEducation_02/ProjectSettings/Physics2DSettings.asset
  UnityEducation_02/ProjectSettings/PresetManager.asset
  UnityEducation_02/ProjectSettings/ProjectSettings.asset
  UnityEducation_02/ProjectSettings/ProjectVersion.txt
  UnityEducation_02/ProjectSettings/QualitySettings.asset
  UnityEducation_02/ProjectSettings/SceneTemplateSettings.json
  UnityEducation_02/ProjectSettings/TagManager.asset
  UnityEducation_02/ProjectSettings/TimeManager.asset
  UnityEducation_02/ProjectSettings/UnityConnectSettings.asset
  UnityEducation_02/ProjectSettings/VFXManager.asset
  UnityEducation_02/ProjectSettings/VersionControlSettings.asset
  UnityEducation_02/ProjectSettings/XRSettings.asset
Labels: checked

#152 [14기 최은별] Unity-2 과제 제출
  최은별/Unity-2/Unity-2_input_action.mp4
Labels: checked

#153 [14기 박시언] - 유니티 과제1, 2
  UnityAssignment/과제1/.gitignore
  UnityAssignment/과제1/Assets/Scenes.meta
  UnityAssignment/과제1/Assets/Scenes/SampleScene.unity
  UnityAssignment/과제1/Assets/Scenes/SampleScene.unity.meta
  UnityAssignment/과제1/Packages/manifest.json
  UnityAssignment/과제1/Packages/packages-lock.json
  UnityAssignment/과제2/.gitignore
  UnityAssignment/과제2/Assembly-CSharp.csproj
  UnityAssignment/과제2/Assets/Scenes.meta
  UnityAssignment/과제2/Assets/Scenes/SampleScene.unity
  UnityAssignment/과제2/Assets/Scenes/SampleScene.unity.meta
  UnityAssignment/과제2/Assets/Scripts.meta
  UnityAssignment/과제2/Assets/Scripts/PlayerController.cs
  UnityAssignment/과제2/Assets/Scripts/PlayerController.cs.meta
  UnityAssignment/과제2/KING_UnityProject_Ex.sln
  UnityAssignment/과제2/Logs/AssetImportWorker0.log
  UnityAssignment/과제2/Logs/AssetImportWorker1.log
  UnityAssignment/과제2/Logs/shadercompiler-AssetImportWorker0.log
  UnityAssignment/과제2/Logs/shadercompiler-UnityShaderCompiler.exe0.log
  UnityAssignment/과제2/Packages/manifest.json
  UnityAssignment/과제2/Packages/packages-lock.json
  UnityAssignment/과제2/obj/Debug/Assembly-CSharp.csproj.AssemblyReference.cache
  UnityAssignment/과제2/obj/Debug/DesignTimeResolveAssemblyReferencesInput.cache
  UnityAssignment/과제2/기능설명
Labels: checked

#158 [14기 전희원] C# 중급 2차시, 유니티 2차시 과제
  Assets/New Controls.inputactions
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/GameManager.cs
  Assets/Scripts/PlayerData.cs
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
  C#중급세션2차시.md
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/ProjectSettings.asset
Labels: checked

#156 [13기 성원희] 유니티 교육세션 1,2차시 과제
  King14_assignmnet/.gitignore
  King14_assignmnet/.vsconfig
  King14_assignmnet/Assets/InputSystem.inputsettings.asset
  King14_assignmnet/Assets/InputSystem.inputsettings.asset.meta
  King14_assignmnet/Assets/MainInputAction.cs
  King14_assignmnet/Assets/MainInputAction.cs.meta
  King14_assignmnet/Assets/MainInputAction.inputactions
  King14_assignmnet/Assets/MainInputAction.inputactions.meta
  King14_assignmnet/Assets/PlayerAction.cs
  King14_assignmnet/Assets/PlayerAction.cs.meta
  King14_assignmnet/Assets/Scenes.meta
  King14_assignmnet/Assets/Scenes/SampleScene.unity
  King14_assignmnet/Assets/Scenes/SampleScene.unity.meta
  King14_assignmnet/Packages/manifest.json
  King14_assignmnet/Packages/packages-lock.json
  King14_assignmnet/ProjectSettings/AudioManager.asset
  King14_assignmnet/ProjectSettings/ClusterInputManager.asset
  King14_assignmnet/ProjectSettings/DynamicsManager.asset
  King14_assignmnet/ProjectSettings/EditorBuildSettings.asset
  King14_assignmnet/ProjectSettings/EditorSettings.asset
  King14_assignmnet/ProjectSettings/GraphicsSettings.asset
  King14_assignmnet/ProjectSettings/InputManager.asset
  King14_assignmnet/ProjectSettings/MemorySettings.asset
  King14_assignmnet/ProjectSettings/NavMeshAreas.asset
  King14_assignmnet/ProjectSettings/NetworkManager.asset
  King14_assignmnet/ProjectSettings/PackageManagerSettings.asset
  King14_assignmnet/ProjectSettings/Physics2DSettings.asset
  King14_assignmnet/ProjectSettings/PresetManager.asset
  King14_assignmnet/ProjectSettings/ProjectSettings.asset
  King14_assignmnet/ProjectSettings/ProjectVersion.txt
  King14_assignmnet/ProjectSettings/QualitySettings.asset
  King14_assignmnet/ProjectSettings/SceneTemplateSettings.json
  King14_assignmnet/ProjectSettings/TagManager.asset
  King14_assignmnet/ProjectSettings/TimeManager.asset
  King14_assignmnet/ProjectSettings/UnityConnectSettings.asset
  King14_assignmnet/ProjectSettings/VFXManager.asset
  King14_assignmnet/ProjectSettings/VersionControlSettings.asset
  King14_assignmnet/ProjectSettings/XRSettings.asset
Labels: checked

#160 [14기 김여은] Unity 세션 2차시 과제 제출
  kye/.gitignore
  kye/unity-2/.vsconfig
  kye/unity-2/Assets/Scenes.meta
  kye/unity-2/Assets/Scenes/SampleScene.unity
  kye/unity-2/Assets/Scenes/SampleScene.unity.meta
  kye/unity-2/Assets/test.cs
  kye/unity-2/Assets/test.cs.meta
  kye/unity-2/Logs/AssetImportWorker0-prev.log
  kye/unity-2/Logs/AssetImportWorker1-prev.log
  kye/unity-2/Logs/Packages-Update.log
  kye/unity-2/Logs/shadercompiler-UnityShaderCompiler.exe0.log
  kye/unity-2/Packages/manifest.json
  kye/unity-2/Packages/packages-lock.json
  kye/unity-2/ProjectSettings/AudioManager.asset
  kye/unity-2/ProjectSettings/ClusterInputManager.asset
  kye/unity-2/ProjectSettings/DynamicsManager.asset
  kye/unity-2/ProjectSettings/EditorBuildSettings.asset
  kye/unity-2/ProjectSettings/EditorSettings.asset
  kye/unity-2/ProjectSettings/GraphicsSettings.asset
  kye/unity-2/ProjectSettings/InputManager.asset
  kye/unity-2/ProjectSettings/MemorySettings.asset
  kye/unity-2/ProjectSettings/NavMeshAreas.asset
  kye/unity-2/ProjectSettings/NetworkManager.asset
  kye/unity-2/ProjectSettings/PackageManagerSettings.asset
  kye/unity-2/ProjectSettings/Physics2DSettings.asset
  kye/unity-2/ProjectSettings/PresetManager.asset
  kye/unity-2/ProjectSettings/ProjectSettings.asset
  kye/unity-2/ProjectSettings/ProjectVersion.txt
  kye/unity-2/ProjectSettings/QualitySettings.asset
  kye/unity-2/ProjectSettings/SceneTemplateSettings.json
  kye/unity-2/ProjectSettings/TagManager.asset
  kye/unity-2/ProjectSettings/TimeManager.asset
  kye/unity-2/ProjectSettings/UnityConnectSettings.asset
  kye/unity-2/ProjectSettings/VFXManager.asset
  kye/unity-2/ProjectSettings/VersionControlSettings.asset
  kye/unity-2/ProjectSettings/XRSettings.asset
  kye/unity-2/UserSettings/EditorUserSettings.asset
  kye/unity-2/UserSettings/Layouts/default-2022.dwlt
  kye/unity-2/UserSettings/Search.settings
  kye/unity-2/obj/Debug/Assembly-CSharp.csproj.AssemblyReference.cache
  kye/unity-2/obj/Debug/DesignTimeResolveAssemblyReferencesInput.cache
Labels: checked
